### ISSUE TITLE
Improvementrequest

### ISSUE THREAD

**Issue by MKleinSB** [1010Technologies/pxt-makerbit-ultrasonic#2]
Hi Phillip!
Is it possible to add a block to raise an event when the distance ist lower than a specified distance?
PS: Sorry, don´t know how to add the improvement Label.

**Comment by philipphenkel** [comment]
@MKleinSB Technically possible, yes. Challenging from the usability perspective. Let's see if we can find a good solution.

**Behaviour**
What would be the behavior you expect? When exactly should the event be triggered? Should it be triggered once when the distance is lower for the first time? Multiple times?

**Event Block**
An event block can come without a parameter.
e.g. onDistanceLessThan10Cm(action)

Or with an enumeration parameter.
e.g. onDistanceLessThan(makerbit.distance10cm, action)
Which values would we need? 5, 10, 15, 20, 25, 50, 100, 150, 200?

**Comment by MKleinSB** [comment]
@philipphenkel 
**Einmal** dachte ich als Bewegungsmelder d.h. jemand geht in einer bestimmten Distanz an einem interaktiven Plakat vorbei --> Der makerbit startet mp3file oder sonstirgendetwas. Dann bräuchte man alles was näher als 1,5m, 1m und 50cm ist.

**Zweite** Anwendung: unkompliziertere Abfrage wie isultraschallless wenn man mit einem Fahrzeug fährt. Für die Kinder (1.-6. Klasse) sind die IF-Abfragen immer unheimlich kompliziert zusammenzubauen. D.h. 5, 10, 15, 20, 30 cm wären meiner Meinung nach dafür geeignet.

Ich denker er sollte nur einmal getriggert werden.

**Comment by philipphenkel** [comment]
Sounds reasonable. From my experience with kids, I agree that event handling is indeed much easier to use.
I will have a look after Easter and come up with a proposal.

@HyperDuino Any thoughts?

**Comment by philipphenkel** [comment]
Implemented and released with version 1.0.5

**Comment by HyperDuino** [comment]
Philipp,

I was trying to use the debug mode of the new release of MakeCode, and 
it seems to be broken.

Here is the program: https://makecode.microbit.org/#pub:_K8geioFF5hvK

But when I step through, it says "no variables" even though "light" is 
right there in the code.

Before I report this as an issue, is there something obvious that I'm 
doing wrong?

Roger

**Comment by philipphenkel** [comment]
Same for me. I don't see variables in MakeCode debug mode as long as I stay with blocks. It works in JavaScript. It's either not yet completely implemented or a bug.

**Comment by MKleinSB** [comment]
Works for me. But you have to make a new variable. Click the red point to watch the variables.
![grafik](https://user-images.githubusercontent.com/37311672/84604108-fad65f00-ae93-11ea-82f4-9d98dfd251b8.png)

**Comment by HyperDuino** [comment]
I clicked on the dot to make it red in my original program (https://makecode.microbit.org/_LsfKaXTebYRR)

![image](https://user-images.githubusercontent.com/13832091/84606750-897bb980-ae5d-11ea-9f89-7511908229c1.png)

Why do I have to make a new variable light2 to get variables to show? Why did "x" work in one program without having the red dot set, but the variable light did not?

**Comment by HyperDuino** [comment]
ok, I get it now about the dots.  That's a break point for the debugger.  

I don't see why light2 works, but light doesn't.
